# Using the node alpine image to build the React app
image: node:alpine

# Announce the URL as per CRA docs
# https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration
variables:
  PUBLIC_URL: /angular-master-detail
cache:
  paths:
  - node_modules

before_script:
  - npm install

# Name the stages involved in the pipeline
stages:
- build
- deploy

build:
  stage: build
  script:
    - npm run test app-example
    - npm run test lib-master-detail
    - npm run build app-example
  artifacts:
    untracked: true
  only:
  - merge_requests
  - master

# Job name for gitlab to recognise this results in assets for Gitlab Pages
# https://docs.gitlab.com/ee/user/project/pages/introduction.html#gitlab-pages-requirements
deploy:
  stage: deploy
  script:
    - npm install # Install all dependencies
    - npm run build --prod app-example # Build for prod
    - cp dist/app-example/index.html dist/app-example/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46
    - mv dist/app-example public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch
